# Generated by Django 4.2.4 on 2023-10-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pybo.question",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="create_date",
            field=models.DateTimeField(),
        ),
    ]
