# Generated by Django 4.0.3 on 2023-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_alter_voca_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('voca_japan', models.CharField(max_length=20)),
                ('voca_korea', models.CharField(max_length=20)),
                ('voca_class', models.CharField(max_length=100)),
            ],
        ),
    ]
